spring:
  application:
    name: mall-search
  profiles:
    active: dev
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          user.name: ${spring.security.user.name}
          user.password: ${spring.security.user.password}
      config:
        server-addr: 127.0.0.1:8848